### ISSUE TITLE
precompiled titan.core fails on Ubuntu 17.10

### ISSUE THREAD

**Issue by frehberg** [eclipse/titan.core#122]
Precompiled binaries expect gcc-5.4.0 as used by Ubuntu-16.04
The precompiled binaries do not work with Ubuntu 17.10 using gcc-7.2.0

http://ftp-stud.fht-esslingen.de/pub/Mirrors/eclipse/titan/ttcn3-6.3.pl0-linux64-gcc5.4-ubuntu16.04.tgz

Not sure the documenation states that the pre-compiled binaries are limited to distros using this specific gcc 5.4.0

The download-page or the README.linux of the  repo should state that these binaries are working on with gcc-5.4.0 only,  such as with Ubuntu 16.04.

Documentation should mention that systems with different gcc-version need to be re-build titan.core binaries using the specific gcc on that system.

**Comment by erititan** [comment]
Hi Frank, 
this is exhaustively documented , see Titan installation guide page 7:

"Warning: the version of C++ compiler used is important. If the version difference between the system’s compiler and the compiler that the basic TTCN–3 library was built with is large enough, the linking of executable test suites will fail with strange error messages. The reason is the different mapping of C++ class and (polymorphic) member function names into linker symbols.
For example, this problem persists between versions 2.8.x and 2.95.x of GCC. Different C++ compilers (e.g. Sun Workshop and GCC) are, of course, totally incompatible.
The solution for this problem is to use nearly the same version of the C++ compiler as the binary package was built with."

Best regards
Elemer
